- name: intall Jenkins
  hosts: nodo1
  become: true
  tasks:
    - name: Install JAVA
      apt:
        name: "openjdk-11-jre"
        update_cache: true
        state: present

    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: "/usr/share/keyrings/jenkins-keyring.asc"

    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install jenkins
      apt:
        name: jenkins
        state: present